"""
Loads ObsInsure synthetic data, generated by synthgen, into the `warehouse`
Postgres database, schema `obsinsure`. Run once after `docker compose up`,
against the exposed Postgres port on localhost.

Reads the eight pipe-delimited, UTF-8-BOM files synthgen's `write_output`
produces. Defaults to the committed
snapshot under warehouse/data/ (see that directory's README for provenance,
the generator command, and the seed); point DATA_DIR elsewhere to load a
freshly generated run instead.

Usage:
    pip install -r requirements.txt
    python load_obsinsure_data.py
"""
import os
from pathlib import Path

import pandas as pd
from sqlalchemy import create_engine

DATA_DIR = Path(os.environ.get("DATA_DIR", Path(__file__).resolve().parent / "data"))
WAREHOUSE_DSN = os.environ.get(
    "WAREHOUSE_DSN", "postgresql://postgres:postgres@localhost:5432/warehouse"
)

# source file -> (table name, index-like id column used as primary key hint)
FILES_TO_TABLES = {
    "catalog.txt": "catalog",
    "contract.txt": "contract",
    "private_party.txt": "private_party",
    "commercial_party.txt": "commercial_party",
    "claim.txt": "claim",
    "premium.txt": "premium",
    "ammendment.txt": "amendment",
    "address.txt": "address",
}


def main() -> None:
    engine = create_engine(WAREHOUSE_DSN)

    for filename, table in FILES_TO_TABLES.items():
        path = DATA_DIR / filename
        if not path.exists():
            print(f"skip {filename}: not found at {path}")
            continue

        df = pd.read_csv(path, sep="|", encoding="utf-8-sig")
        df.to_sql(
            table,
            engine,
            schema="obsinsure",
            if_exists="replace",
            index=False,
        )
        print(f"loaded {len(df):>6} rows -> obsinsure.{table}")


if __name__ == "__main__":
    main()
